name: ${project.artifactId}
version: ${project.version}
main: de.brightstorm.payday
softdepend: [Vault, Essentials]
dev-url: http://dev.bukkit.org/server-mods/payday/
commands:
  payday:
    permission: payday.admincommand
  paycheck:
    description: Check time.
